dma-buf: dma-buf-trace: Include missing compat.h header
../drivers/dma-buf/dma-buf-trace.c:663:12: error: implicit declaration of function 'compat_ptr' [-Werror,-Wimplicit-function-declaration]
  663 |                 uflags = compat_ptr(cptr);
      |                          ^
../drivers/dma-buf/dma-buf-trace.c:663:10: error: incompatible integer to pointer conversion assigning to 'unsigned int *' from 'int' [-Wint-conversion]
  663 |                 uflags = compat_ptr(cptr);
      |                        ^ ~~~~~~~~~~~~~~~~
../drivers/dma-buf/dma-buf-trace.c:708:11: error: implicit declaration of function 'compat_ptr' [-Werror,-Wimplicit-function-declaration]
  708 |                 usize = compat_ptr(cptr);
      |                         ^
../drivers/dma-buf/dma-buf-trace.c:708:9: error: incompatible integer to pointer conversion assigning to 'int *' from 'int' [-Wint-conversion]
  708 |                 usize = compat_ptr(cptr);
      |                       ^ ~~~~~~~~~~~~~~~~
4 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>