drivers: sensors: vl53l5: suppress unused-but-set-variable error
Fixes error:
../drivers/sensors/vl53l5/platform/src/vl53l5_platform_log.c:71:17: error: variable '_trace_modules' set but not used [-Werror,-Wunused-but-set-global]
   71 | static uint32_t _trace_modules   = VL53L5_TRACE_MODULE_ALL;
      |                 ^
1 error generated.

Signed-off-by: xfwdrev <74693315+xfwdrev@users.noreply.github.com>